# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h5_Paj_oz6BZvnl3t-HJa_WxIqFkYSk2

# Wedding invitation for Arsha and Ashiq
"""

brides_name = "T.Arsha Fahima"
grooms_name = "Y.Ashiq Meeran"
grooms_parents_name = "H.Yusuf NallaMeera,Y.Nargis Yusuf"
date = "31/Jan/2027"
time = "11:30 Am"
venu = "Agustus Mahal"

madlab = f"We are so overwhelmed by happiness as we announce the wedding ceremony of our beloved daughter. We invite you to bless him and her for the new life.We request you to bless us all with your presence on {date} at {venu} as we gather to celebrate the holy bond of the marriage of our daughter !. Our beloved daughter {brides_name} is getting married with {grooms_name}, son of {grooms_parents_name} with your blessings on {date} at {time}. Please be there for our little girl and bless them.We are excited to let you know that we have made all the arrangements to marry our daughter and son off with in the name of NIKKAh on {date}.  Hope you'd be kind enough to join us and make this day brighter.This day for us is special\n\tA time beyond compare\n\tThe joy we feel deep in our hearts\n\tWe hope you will come and share\n\tYour presence there with us\n\tMeans more than words can say\n\tPlease try to be there\n\tTo celebrate this special day."

print(madlab)